version: '3.7'

services:
  # Main web application
  kali-desktop:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: kali-desktop
    container_name: kali-desktop
    command: npm start
    volumes:
      - './:/kali'
      - node_modules:/kali/node_modules/
    ports:
      - 4200:4200
    networks:
      - kali-network

volumes:
  node_modules:

networks:
  kali-network:
    driver: bridge
